# Generated by Django 3.2.6 on 2022-09-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='category_img',
        ),
    ]
