# Generated by Django 3.2.6 on 2022-12-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='created',
        ),
        migrations.AddField(
            model_name='blog',
            name='reading_time',
            field=models.IntegerField(default=2, max_length=2),
        ),
    ]
