# Generated by Django 3.2.6 on 2022-12-21 07:10

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20221219_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img_opt',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=0.5, size=[1020, 660], upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='reading_time',
            field=models.IntegerField(default=2),
        ),
    ]
