# Generated by Django 3.2.6 on 2022-09-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='music',
            field=models.FileField(default=1, upload_to='music'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
