# Generated by Django 3.2.6 on 2022-12-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20221221_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img_alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
