# Generated by Django 3.2.6 on 2022-12-21 07:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_blog_img_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_url',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
