# Generated by Django 3.2.6 on 2022-12-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220926_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='music'),
        ),
    ]
