# Generated by Django 3.2.6 on 2022-12-28 13:34

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_blog_blog_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='music',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_meta',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img_alt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='keywords_meta',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blog',
            name='snipit',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_meta',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='category'),
        ),
        migrations.CreateModel(
            name='Post_of_the_month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.blog')),
            ],
        ),
    ]
